### ISSUE TITLE
Create "User Management" page

### ISSUE THREAD

**Issue by zhwatts** [BluelineInnovations/NG.FE#9]
**Add a page to allow for creating new and managing existing users.**
Page should feature a form to manage the required and optional user properties. A list of all existing users should be present for a user to quickly select from, which will then fill the form so the agency may be edited.

### Task categories
- [ ] Determine what content will be required for the page model
- [ ]  Work with backend to create or modify any required endpoints
- [ ] Work with @buihdk to establish required state actions and reductions
- [ ] implement Material UI design
